name: LangSwitch
version: 1.0.0
description: Create links to corresponding languages on your site
url: https://github.com/lesaff/statamicv2-lang_switch
developer: 'Jason Varga & Rudy Affandi (v2 conversion)'
developer_url: https://github.com/lesaff
